apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: gst-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: nilk3391/api-gateway:latest.v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_CONFIG_LOCATION
              value: file:/config/application.properties
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: api-gateway-config
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: gst-app
spec:
  type: LoadBalancer
  selector:
    app: api-gateway
  ports:
    - port: 8085
      targetPort: 8085
