apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: gst-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: nilk3391/auth-service:latest.v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_CONFIG_LOCATION
              value: file:/config/application.properties
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: auth-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: gst-app
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - port: 8084
      targetPort: 8084