apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: gst-app
spec:
  replicas: 1
  selector:
    matchLabels: { app: eureka-server }
  template:
    metadata:
      labels: { app: eureka-server }
    spec:
      containers:
        - name: eureka-server
          image: nilk3391/eureka-server:latest
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 8761 }]
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
              scheme: HTTP
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: gst-app
spec:
  selector: { app: eureka-server }
  ports:
    - port: 8761
      targetPort: 8761
      name: http