apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-service
  namespace: gst-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoice-service
  template:
    metadata:
      labels:
        app: invoice-service
    spec:
      containers:
        - name: invoice-service
          image: nilk3391/invoice-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_CONFIG_LOCATION
              value: file:/config/application.properties
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: invoice-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: invoice-service
  namespace: gst-app
spec:
  type: ClusterIP
  selector:
    app: invoice-service
  ports:
    - port: 8082
      targetPort: 8082
