apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: gst-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: nilk3391/user-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CONFIG_LOCATION
              value: file:/config/application.properties
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: user-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: gst-app
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
    - port: 8081
      targetPort: 8081
