apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector: { matchLabels: { app: auth-service } }
  template:
    metadata:
      labels: { app: auth-service }
    spec:
      containers:
        - name: auth-service
          image: nilk3391/auth-service:latest
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 8084 }]
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector: { app: auth-service }
  ports: [{ port: 8084, targetPort: 8084, name: http }]